
# version: '3.8'

services:
  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env  # Charge les variables depuis ce fichier
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - foodfask_net

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5433:5432"  # Port hôte:conteneur
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - foodfask_net

volumes:
  pgdata:

networks:
  foodfask_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16